// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoe7AhxuGXBg--RWl16oa3lJgeTDQ08c',
    appId: '1:299090577035:web:d218ce04b49b0e7cecb68e',
    messagingSenderId: '299090577035',
    projectId: 'weardo',
    authDomain: 'weardo.firebaseapp.com',
    storageBucket: 'weardo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBABvUvDoV3J8FFX2wgN4h2Wk6slqxRqcc',
    appId: '1:299090577035:android:2ecdb1382a48f83cecb68e',
    messagingSenderId: '299090577035',
    projectId: 'weardo',
    storageBucket: 'weardo.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrPOVRc3iW28FxGb7b61PIsGbes0IbmTc',
    appId: '1:299090577035:ios:0da4f327ea1dc1c5ecb68e',
    messagingSenderId: '299090577035',
    projectId: 'weardo',
    storageBucket: 'weardo.firebasestorage.app',
    iosBundleId: 'com.example.weardoOutfitBuilder',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrPOVRc3iW28FxGb7b61PIsGbes0IbmTc',
    appId: '1:299090577035:ios:0da4f327ea1dc1c5ecb68e',
    messagingSenderId: '299090577035',
    projectId: 'weardo',
    storageBucket: 'weardo.firebasestorage.app',
    iosBundleId: 'com.example.weardoOutfitBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVoe7AhxuGXBg--RWl16oa3lJgeTDQ08c',
    appId: '1:299090577035:web:5b45f714bba283d7ecb68e',
    messagingSenderId: '299090577035',
    projectId: 'weardo',
    authDomain: 'weardo.firebaseapp.com',
    storageBucket: 'weardo.firebasestorage.app',
  );

}